### PR TITLE
Do not treat a sharp in code quotes as a heading.

### PR DESCRIPTION
**Pull request by erictune**

### CODE REVIEW

**Comment by erictune** [comment]
Fixes #8

**Comment by aslushnikov** [comment]
Please, put `01-code.md`/`01-code.expected` into the `generic` folder. The `generic` is the one which contains all tests to run without any runtime flags.

**Comment by erictune** [comment]
Moved.

**Comment by aslushnikov** [comment]
Thank you!

**Comment by erictune** [comment]
Thanks for taking this!

**Pull request merged**
